### ISSUE TITLE
Isolate the ICU library in another module

### ISSUE THREAD

**Issue by pith** [seedstack/i18n-addon#1]
The i18n function is quite heavy due to the ICU library. It would be interesting to isolate it in another module. This will avoid to weigh down projects that only need few locales.

**Comment by ydautremay** [comment]
ICU allows to format Dates in String with many predefined formats corresponding to locales. Even if you only need one locale, say en-us, removing ICU would mean not knowing that a Date is written mm/dd/yyyy. Just saying...

**Comment by pith** [comment]
Won't be fix in a close future. Reopen if required.
