### ISSUE TITLE
What if we want to use another persistence than JPA ?

### ISSUE THREAD

**Issue by pith** [seedstack/i18n-addon#3]
What should we do if we wanted to use another persistence ?

1. Nothing. We won't support that
2. Put the JPA infrastructure in a separate JAR
3. Add other persistences in the Core JAR and provide a way to choose via configuration

I think the second would be the good one, the only annoying thing would be that you will have to specify two jar instead of one (web + persistence).

**Comment by adrienlauer** [comment]
The second option, definitely. I think that the small inconvenience of having two jars is not a problem and putting all the persistence implementations in the same jar would be problematic. 

We can think about it though, because we cannot increase the jar count for every small feature forever.

**Comment by pith** [comment]
Reopen the issue when it'll be by someone
