### ISSUE TITLE
Encoding problem in translation export

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/i18n-addon#6]
Exporting translations to CSV seems to produce encoding errors with accentuated characters. This issue is not yet confirmed but writing an integration test for it might be a good idea, regardless of its validity. Then we should fix it if necessary.

**Comment by pith** [comment]
It doesn't produce encoding errors but `UTF-8` which is not the default charset in Excel. So I can add a configuration option if the users want to use `cp1252` by default ...
Or I have found that ICU (which is used by the i18n addon) can detect the charset in text: http://userguide.icu-project.org/conversion/detection
